# Modified from https://github.com/joinmisskey/misskey-tga

name: Deploy test environment
on:
  workflow_call:
    inputs:
      branch_or_hash:
        type: string
        required: true
  workflow_dispatch:
    inputs:
      branch_or_hash:
        type: string
        required: true

jobs:
  deploy-test-environment:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    env:
      GH_TOKEN: ${{ github.token }}
      REPOSITORY: 'FineArchs/misskey'
      DEVENVREPO: 'FineArchs/midevenv'
      WAIT_TIME: 1800

    steps:
    - name: Setup environment variables
      run: |
        {
          echo "BRANCH_OR_HASH="${{ inputs.branch_or_hash }}
          # for tput command pnpm
          echo "TERM=xterm"
          # directories
          echo "MISSKEY_DIR=$(pwd)/misskey"
          echo "SCRIPTS_DIR=$(pwd)/deploy"
        } >> $GITHUB_ENV

    - name: Checkout Deploying Scripts
      uses: actions/checkout@v4
      with:
        sparse-checkout: deploy

    - name: Checkout misskey
      uses: actions/checkout@v4
      with:
        path: ${{ env.MISSKEY_DIR }}
        repository: ${{ env.REPOSITORY }}
        submodules: true
        ref: ${{ env.BRANCH_OR_HASH }}
  
    - name: Get the latest commit SHA
      run: |
        pushd misskey
        echo "SHA="$(git rev-parse HEAD) >> $GITHUB_ENV
        popd

    - name: Install cloudflared
      run: |
        wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
        sudo dpkg -i cloudflared-linux-amd64.deb

    - name: Start cloudflare tunnel (misskey)
      run: bash $SCRIPTS_DIR/tunnel.sh
      env:
        PORT: 3000
        METRICS_PORT: 55555
        ENV_NAME: MISSKEY_URL

    - name: Start cloudflare tunnel (migration trigger)
      run: bash $SCRIPTS_DIR/tunnel.sh
      env:
        PORT: 3001
        METRICS_PORT: 55556
        ENV_NAME: MIDTRIGGER_URL

    - name: Setup pnpm
      uses: pnpm/action-setup@v4.1.0
      working-directory: ${{ env.MISSKEY_DIR }}
    - name: Setup Nodejs
      uses: actions/setup-node@v4.3.0
      working-directory: ${{ env.MISSKEY_DIR }}
      with:
        node-version-file: '.node-version'
        cache: 'pnpm'

    - name: Setup misskey
      run: |
        . $SCRIPTS_DIR/init.sh &
        echo $! > $SCRIPTS_DIR/.migrate-pid

    - name: Start Migration Trigger
      env:
        PORT: 3001
      run: |
        cd $SCRIPTS_DIR
        pnpm i --frozen-lockfile
        pnpm start &

    - run: |
        CURRENT_TIME=$(TZ=Asia/Tokyo date +'%Y-%m-%d %H:%M:%S JST')
        echo "CURRENT_TIME=$CURRENT_TIME" >> $GITHUB_ENV
        COMMIT_URL="https://github.com/$REPOSITORY/commit/$SHA"
        echo "COMMIT_URL=$COMMIT_URL" >> $GITHUB_ENV

    - name: Comment
      env: 
        BODY: |-
          URL: https://${{ env.MISSKEY_URL }}
          MIGRATION_URL: https://${{ env.MIGTRIGGER_URL }}
          Repository: ${{ env.REPOSITORY }}
          Branch or Commit hash: ${{ env.BRANCH_OR_HASH }}
          Commit: ${{ env.COMMIT_URL }}
          Time: ${{ env.CURRENT_TIME }}
      run: |
        gh issue comment 1 -R $DEVENVREPO -b "$BODY"
    - name: Wait
      run: |
        timeout $WAIT_TIME tail -f /var/log/syslog || true
