# Modified from https://github.com/joinmisskey/misskey-tga

name: Deploy test environment
on:
  workflow_call:
    inputs:
      branch_or_hash:
        type: string
        required: true
  workflow_dispatch:
    inputs:
      branch_or_hash:
        type: string
        required: true

jobs:
  deploy-test-environment:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    env:
      GH_TOKEN: ${{ github.token }}
      REPOSITORY: 'FineArchs/misskey'
      DEVENVREPO: 'FineArchs/midevenv'
      WAIT_TIME: 1800

    steps:
    - name: Set environment variable (for tput command & pnpm)
      run: |
        echo "TERM=xterm" >> $GITHUB_ENV
        BRANCH_OR_HASH=${{ inputs.branch_or_hash }}
        echo "BRANCH_OR_HASH=$BRANCH_OR_HASH" >> $GITHUB_ENV

    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: ${{ env.REPOSITORY }}
        submodules: true
        ref: ${{ env.BRANCH_OR_HASH }}
  
    - name: Get the latest commit SHA
      run: |
        SHA=$(git log -1 --format="%H")
        echo "SHA=$SHA" >> $GITHUB_ENV

    - name: Start cloudflare tunnel (quick)
      run: |
        wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
        sudo dpkg -i cloudflared-linux-amd64.deb
        sudo cloudflared tunnel --metrics localhost:55555 --url localhost:3000 > /dev/null 2>&1 &
        sleep 15
        TUNNEL_RESPONSE=$(curl http://localhost:55555/quicktunnel)
        TUNNEL_DOMAIN=$(echo $TUNNEL_RESPONSE | grep -o '"hostname":"[^"]*' | grep -o '[^"]*$')
        echo "::add-mask::$TUNNEL_DOMAIN"
        echo "TUNNEL_DOMAIN=$TUNNEL_DOMAIN" >> $GITHUB_ENV

    - name: Install misskey
      run: |
        wget https://raw.githubusercontent.com/joinmisskey/bash-install/v4/misskey-install.sh
        wget https://raw.githubusercontent.com/joinmisskey/bash-install/v4/testenv_githubactions.txt
        sed -i "2i set -exo pipefail"
        sed -i "s/host=127.0.0.1/host=$TUNNEL_DOMAIN/g" testenv_githubactions.txt
        sed -i "s|git_repository=https://github.com/misskey-dev/misskey|git_repository=https://github.com/$REPOSITORY|g" testenv_githubactions.txt
        sed -i "s|git_branch=master|git_branch=$BRANCH_OR_HASH|g" testenv_githubactions.txt
        sudo chmod 555 ./misskey-install.sh
        sudo bash -x ./misskey-install.sh -c ./testenv_githubactions.txt

    - run: |
        CURRENT_TIME=$(TZ=Asia/Tokyo date +'%Y-%m-%d %H:%M:%S JST')
        echo "CURRENT_TIME=$CURRENT_TIME" >> $GITHUB_ENV
        COMMIT_URL="https://github.com/$REPOSITORY/commit/$SHA"
        echo "COMMIT_URL=$COMMIT_URL" >> $GITHUB_ENV
    - name: Comment
      env: 
        BODY: |-
          URL: https://${{ env.TUNNEL_DOMAIN }}
          Repository: ${{ env.REPOSITORY }}
          Branch or Commit hash: ${{ env.BRANCH_OR_HASH }}
          Commit: ${{ env.COMMIT_URL }}
          Time: ${{ env.CURRENT_TIME }}
      run: |
        gh issue comment 1 -R $DEVENVREPO -b "$BODY"
    - name: Wait
      run: |
        timeout $WAIT_TIME tail -f /var/log/syslog || true
