name: Deploy from timeline
on:
  issue_comment:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{
        (github.event.issue.number == 1)
        && (github.actor == github.repository_owner)
      }}
    outputs:
      branch_or_hash: ${{ steps.parse.outputs.branch_or_hash }}
    steps:
      - id: parse
        env:
          COMMENT: ${{ github.event.comment.body }}
        run: |
          outputs=(
            'branch_or_hash'
          )
          IFS=$'\n'
          readarray -t values <<< "$COMMENT"
          for i in ${!outputs[@]}; do
            echo "${outputs[i]}=${values[i]}" >> $GITHUB_OUTPUT
          done

  call:
    needs: deploy
    uses: ./.github/workflows/deploy.yml
    with:
      branch_or_hash: ${{ needs.deploy.outputs.branch_or_hash }}
