name: Deploy from timeline
on:
  issue_comment:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{
        (github.event.issue.number == 1)
        && (github.actor == github.repository_owner)
      }}
    steps:
      - name: parse
        env:
          COMMENT: ${{ github.event.comment.body }}
        run: |
          variables=(
            'BRANCH_OR_HASH'
          )
          echo A $variables
          IFS=$'\n'
          echo A2 $IFS
          read -r -d '' -a values <<< "$COMMENT"
          echo B $values
          for i in ${!variables[@]}; do
            echo "${variables[i]}=${values[i]}" >> $GITHUB_ENV
          done

      - name: call
        uses: ./deploy.yml
        with:
           branch_or_hash: ${{ env.BRANCH_OR_HASH }}
